// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: tests/testdata/album.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_CD      Format = 0
	Format_DIGITAL Format = 1
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "CD",
		1: "DIGITAL",
	}
	Format_value = map[string]int32{
		"CD":      0,
		"DIGITAL": 1,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_testdata_album_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_tests_testdata_album_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_tests_testdata_album_proto_rawDescGZIP(), []int{0}
}

type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        *Singer                `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ReleaseYear   int32                  `protobuf:"varint,3,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	Format        Format                 `protobuf:"varint,4,opt,name=format,proto3,enum=execute_query.test.Format" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_tests_testdata_album_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_tests_testdata_album_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_tests_testdata_album_proto_rawDescGZIP(), []int{0}
}

func (x *Album) GetArtist() *Singer {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *Album) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Album) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *Album) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_CD
}

var File_tests_testdata_album_proto protoreflect.FileDescriptor

const file_tests_testdata_album_proto_rawDesc = "" +
	"\n" +
	"\x1atests/testdata/album.proto\x12\x12execute_query.test\x1a\x1btests/testdata/singer.proto\"\xa8\x01\n" +
	"\x05Album\x122\n" +
	"\x06artist\x18\x01 \x01(\v2\x1a.execute_query.test.SingerR\x06artist\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\frelease_year\x18\x03 \x01(\x05R\vreleaseYear\x122\n" +
	"\x06format\x18\x04 \x01(\x0e2\x1a.execute_query.test.FormatR\x06format*\x1d\n" +
	"\x06Format\x12\x06\n" +
	"\x02CD\x10\x00\x12\v\n" +
	"\aDIGITAL\x10\x01BIZGgithub.com/googleapis/cloud-bigtable-clients-test/tests/testdata;testpbb\x06proto3"

var (
	file_tests_testdata_album_proto_rawDescOnce sync.Once
	file_tests_testdata_album_proto_rawDescData []byte
)

func file_tests_testdata_album_proto_rawDescGZIP() []byte {
	file_tests_testdata_album_proto_rawDescOnce.Do(func() {
		file_tests_testdata_album_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_testdata_album_proto_rawDesc), len(file_tests_testdata_album_proto_rawDesc)))
	})
	return file_tests_testdata_album_proto_rawDescData
}

var file_tests_testdata_album_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tests_testdata_album_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_testdata_album_proto_goTypes = []any{
	(Format)(0),    // 0: execute_query.test.Format
	(*Album)(nil),  // 1: execute_query.test.Album
	(*Singer)(nil), // 2: execute_query.test.Singer
}
var file_tests_testdata_album_proto_depIdxs = []int32{
	2, // 0: execute_query.test.Album.artist:type_name -> execute_query.test.Singer
	0, // 1: execute_query.test.Album.format:type_name -> execute_query.test.Format
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tests_testdata_album_proto_init() }
func file_tests_testdata_album_proto_init() {
	if File_tests_testdata_album_proto != nil {
		return
	}
	file_tests_testdata_singer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_testdata_album_proto_rawDesc), len(file_tests_testdata_album_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_testdata_album_proto_goTypes,
		DependencyIndexes: file_tests_testdata_album_proto_depIdxs,
		EnumInfos:         file_tests_testdata_album_proto_enumTypes,
		MessageInfos:      file_tests_testdata_album_proto_msgTypes,
	}.Build()
	File_tests_testdata_album_proto = out.File
	file_tests_testdata_album_proto_goTypes = nil
	file_tests_testdata_album_proto_depIdxs = nil
}
