// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: tests/testdata/singer.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genre int32

const (
	Genre_POP  Genre = 0
	Genre_JAZZ Genre = 1
	Genre_FOLK Genre = 2
	Genre_ROCK Genre = 3
)

// Enum value maps for Genre.
var (
	Genre_name = map[int32]string{
		0: "POP",
		1: "JAZZ",
		2: "FOLK",
		3: "ROCK",
	}
	Genre_value = map[string]int32{
		"POP":  0,
		"JAZZ": 1,
		"FOLK": 2,
		"ROCK": 3,
	}
)

func (x Genre) Enum() *Genre {
	p := new(Genre)
	*p = x
	return p
}

func (x Genre) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Genre) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_testdata_singer_proto_enumTypes[0].Descriptor()
}

func (Genre) Type() protoreflect.EnumType {
	return &file_tests_testdata_singer_proto_enumTypes[0]
}

func (x Genre) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Genre.Descriptor instead.
func (Genre) EnumDescriptor() ([]byte, []int) {
	return file_tests_testdata_singer_proto_rawDescGZIP(), []int{0}
}

type Singer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Genre         Genre                  `protobuf:"varint,2,opt,name=genre,proto3,enum=execute_query.test.Genre" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Singer) Reset() {
	*x = Singer{}
	mi := &file_tests_testdata_singer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Singer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Singer) ProtoMessage() {}

func (x *Singer) ProtoReflect() protoreflect.Message {
	mi := &file_tests_testdata_singer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Singer.ProtoReflect.Descriptor instead.
func (*Singer) Descriptor() ([]byte, []int) {
	return file_tests_testdata_singer_proto_rawDescGZIP(), []int{0}
}

func (x *Singer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Singer) GetGenre() Genre {
	if x != nil {
		return x.Genre
	}
	return Genre_POP
}

var File_tests_testdata_singer_proto protoreflect.FileDescriptor

const file_tests_testdata_singer_proto_rawDesc = "" +
	"\n" +
	"\x1btests/testdata/singer.proto\x12\x12execute_query.test\"M\n" +
	"\x06Singer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x05genre\x18\x02 \x01(\x0e2\x19.execute_query.test.GenreR\x05genre*.\n" +
	"\x05Genre\x12\a\n" +
	"\x03POP\x10\x00\x12\b\n" +
	"\x04JAZZ\x10\x01\x12\b\n" +
	"\x04FOLK\x10\x02\x12\b\n" +
	"\x04ROCK\x10\x03BIZGgithub.com/googleapis/cloud-bigtable-clients-test/tests/testdata;testpbb\x06proto3"

var (
	file_tests_testdata_singer_proto_rawDescOnce sync.Once
	file_tests_testdata_singer_proto_rawDescData []byte
)

func file_tests_testdata_singer_proto_rawDescGZIP() []byte {
	file_tests_testdata_singer_proto_rawDescOnce.Do(func() {
		file_tests_testdata_singer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_testdata_singer_proto_rawDesc), len(file_tests_testdata_singer_proto_rawDesc)))
	})
	return file_tests_testdata_singer_proto_rawDescData
}

var file_tests_testdata_singer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tests_testdata_singer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_testdata_singer_proto_goTypes = []any{
	(Genre)(0),     // 0: execute_query.test.Genre
	(*Singer)(nil), // 1: execute_query.test.Singer
}
var file_tests_testdata_singer_proto_depIdxs = []int32{
	0, // 0: execute_query.test.Singer.genre:type_name -> execute_query.test.Genre
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tests_testdata_singer_proto_init() }
func file_tests_testdata_singer_proto_init() {
	if File_tests_testdata_singer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_testdata_singer_proto_rawDesc), len(file_tests_testdata_singer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_testdata_singer_proto_goTypes,
		DependencyIndexes: file_tests_testdata_singer_proto_depIdxs,
		EnumInfos:         file_tests_testdata_singer_proto_enumTypes,
		MessageInfos:      file_tests_testdata_singer_proto_msgTypes,
	}.Build()
	File_tests_testdata_singer_proto = out.File
	file_tests_testdata_singer_proto_goTypes = nil
	file_tests_testdata_singer_proto_depIdxs = nil
}
