// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: test_proxy.proto

package testproxypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CloudBigtableV2TestProxy_CreateClient_FullMethodName       = "/google.bigtable.testproxy.CloudBigtableV2TestProxy/CreateClient"
	CloudBigtableV2TestProxy_CloseClient_FullMethodName        = "/google.bigtable.testproxy.CloudBigtableV2TestProxy/CloseClient"
	CloudBigtableV2TestProxy_RemoveClient_FullMethodName       = "/google.bigtable.testproxy.CloudBigtableV2TestProxy/RemoveClient"
	CloudBigtableV2TestProxy_ReadRow_FullMethodName            = "/google.bigtable.testproxy.CloudBigtableV2TestProxy/ReadRow"
	CloudBigtableV2TestProxy_ReadRows_FullMethodName           = "/google.bigtable.testproxy.CloudBigtableV2TestProxy/ReadRows"
	CloudBigtableV2TestProxy_MutateRow_FullMethodName          = "/google.bigtable.testproxy.CloudBigtableV2TestProxy/MutateRow"
	CloudBigtableV2TestProxy_BulkMutateRows_FullMethodName     = "/google.bigtable.testproxy.CloudBigtableV2TestProxy/BulkMutateRows"
	CloudBigtableV2TestProxy_CheckAndMutateRow_FullMethodName  = "/google.bigtable.testproxy.CloudBigtableV2TestProxy/CheckAndMutateRow"
	CloudBigtableV2TestProxy_SampleRowKeys_FullMethodName      = "/google.bigtable.testproxy.CloudBigtableV2TestProxy/SampleRowKeys"
	CloudBigtableV2TestProxy_ReadModifyWriteRow_FullMethodName = "/google.bigtable.testproxy.CloudBigtableV2TestProxy/ReadModifyWriteRow"
	CloudBigtableV2TestProxy_ExecuteQuery_FullMethodName       = "/google.bigtable.testproxy.CloudBigtableV2TestProxy/ExecuteQuery"
)

// CloudBigtableV2TestProxyClient is the client API for CloudBigtableV2TestProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Note that all RPCs are unary, even when the equivalent client binding call
// may be streaming. This is an intentional simplification.
//
// Most methods have sync (default) and async variants. For async variants,
// the proxy is expected to perform the async operation, then wait for results
// before delivering them back to the driver client.
//
// Operations that may have interesting concurrency characteristics are
// represented explicitly in the API (see ReadRowsRequest.cancel_after_rows).
// We include such operations only when they can be meaningfully performed
// through client bindings.
//
// Users should generally avoid setting deadlines for requests to the Proxy
// because operations are not cancelable. If the deadline is set anyway, please
// understand that the underlying operation will continue to be executed even
// after the deadline expires.
type CloudBigtableV2TestProxyClient interface {
	// Client management:
	//
	// Creates a client in the proxy.
	// Each client has its own dedicated channel(s), and can be used concurrently
	// and independently with other clients.
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	// Closes a client in the proxy, making it not accept new requests.
	CloseClient(ctx context.Context, in *CloseClientRequest, opts ...grpc.CallOption) (*CloseClientResponse, error)
	// Removes a client in the proxy, making it inaccessible. Client closing
	// should be done by CloseClient() separately.
	RemoveClient(ctx context.Context, in *RemoveClientRequest, opts ...grpc.CallOption) (*RemoveClientResponse, error)
	// Bigtable operations: for each operation, you should use the synchronous or
	// asynchronous variant of the client method based on the `use_async_method`
	// setting of the client instance. For starters, you can choose to implement
	// one variant, and return UNIMPLEMENTED status for the other.
	//
	// Reads a row with the client instance.
	// The result row may not be present in the response.
	// Callers should check for it (e.g. calling has_row() in C++).
	ReadRow(ctx context.Context, in *ReadRowRequest, opts ...grpc.CallOption) (*RowResult, error)
	// Reads rows with the client instance.
	ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (*RowsResult, error)
	// Writes a row with the client instance.
	MutateRow(ctx context.Context, in *MutateRowRequest, opts ...grpc.CallOption) (*MutateRowResult, error)
	// Writes multiple rows with the client instance.
	BulkMutateRows(ctx context.Context, in *MutateRowsRequest, opts ...grpc.CallOption) (*MutateRowsResult, error)
	// Performs a check-and-mutate-row operation with the client instance.
	CheckAndMutateRow(ctx context.Context, in *CheckAndMutateRowRequest, opts ...grpc.CallOption) (*CheckAndMutateRowResult, error)
	// Obtains a row key sampling with the client instance.
	SampleRowKeys(ctx context.Context, in *SampleRowKeysRequest, opts ...grpc.CallOption) (*SampleRowKeysResult, error)
	// Performs a read-modify-write operation with the client.
	ReadModifyWriteRow(ctx context.Context, in *ReadModifyWriteRowRequest, opts ...grpc.CallOption) (*RowResult, error)
	// Executes a SQL query with the client.
	ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResult, error)
}

type cloudBigtableV2TestProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudBigtableV2TestProxyClient(cc grpc.ClientConnInterface) CloudBigtableV2TestProxyClient {
	return &cloudBigtableV2TestProxyClient{cc}
}

func (c *cloudBigtableV2TestProxyClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, CloudBigtableV2TestProxy_CreateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudBigtableV2TestProxyClient) CloseClient(ctx context.Context, in *CloseClientRequest, opts ...grpc.CallOption) (*CloseClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseClientResponse)
	err := c.cc.Invoke(ctx, CloudBigtableV2TestProxy_CloseClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudBigtableV2TestProxyClient) RemoveClient(ctx context.Context, in *RemoveClientRequest, opts ...grpc.CallOption) (*RemoveClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveClientResponse)
	err := c.cc.Invoke(ctx, CloudBigtableV2TestProxy_RemoveClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudBigtableV2TestProxyClient) ReadRow(ctx context.Context, in *ReadRowRequest, opts ...grpc.CallOption) (*RowResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RowResult)
	err := c.cc.Invoke(ctx, CloudBigtableV2TestProxy_ReadRow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudBigtableV2TestProxyClient) ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (*RowsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RowsResult)
	err := c.cc.Invoke(ctx, CloudBigtableV2TestProxy_ReadRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudBigtableV2TestProxyClient) MutateRow(ctx context.Context, in *MutateRowRequest, opts ...grpc.CallOption) (*MutateRowResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutateRowResult)
	err := c.cc.Invoke(ctx, CloudBigtableV2TestProxy_MutateRow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudBigtableV2TestProxyClient) BulkMutateRows(ctx context.Context, in *MutateRowsRequest, opts ...grpc.CallOption) (*MutateRowsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutateRowsResult)
	err := c.cc.Invoke(ctx, CloudBigtableV2TestProxy_BulkMutateRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudBigtableV2TestProxyClient) CheckAndMutateRow(ctx context.Context, in *CheckAndMutateRowRequest, opts ...grpc.CallOption) (*CheckAndMutateRowResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAndMutateRowResult)
	err := c.cc.Invoke(ctx, CloudBigtableV2TestProxy_CheckAndMutateRow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudBigtableV2TestProxyClient) SampleRowKeys(ctx context.Context, in *SampleRowKeysRequest, opts ...grpc.CallOption) (*SampleRowKeysResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SampleRowKeysResult)
	err := c.cc.Invoke(ctx, CloudBigtableV2TestProxy_SampleRowKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudBigtableV2TestProxyClient) ReadModifyWriteRow(ctx context.Context, in *ReadModifyWriteRowRequest, opts ...grpc.CallOption) (*RowResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RowResult)
	err := c.cc.Invoke(ctx, CloudBigtableV2TestProxy_ReadModifyWriteRow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudBigtableV2TestProxyClient) ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteQueryResult)
	err := c.cc.Invoke(ctx, CloudBigtableV2TestProxy_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudBigtableV2TestProxyServer is the server API for CloudBigtableV2TestProxy service.
// All implementations must embed UnimplementedCloudBigtableV2TestProxyServer
// for forward compatibility.
//
// Note that all RPCs are unary, even when the equivalent client binding call
// may be streaming. This is an intentional simplification.
//
// Most methods have sync (default) and async variants. For async variants,
// the proxy is expected to perform the async operation, then wait for results
// before delivering them back to the driver client.
//
// Operations that may have interesting concurrency characteristics are
// represented explicitly in the API (see ReadRowsRequest.cancel_after_rows).
// We include such operations only when they can be meaningfully performed
// through client bindings.
//
// Users should generally avoid setting deadlines for requests to the Proxy
// because operations are not cancelable. If the deadline is set anyway, please
// understand that the underlying operation will continue to be executed even
// after the deadline expires.
type CloudBigtableV2TestProxyServer interface {
	// Client management:
	//
	// Creates a client in the proxy.
	// Each client has its own dedicated channel(s), and can be used concurrently
	// and independently with other clients.
	CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	// Closes a client in the proxy, making it not accept new requests.
	CloseClient(context.Context, *CloseClientRequest) (*CloseClientResponse, error)
	// Removes a client in the proxy, making it inaccessible. Client closing
	// should be done by CloseClient() separately.
	RemoveClient(context.Context, *RemoveClientRequest) (*RemoveClientResponse, error)
	// Bigtable operations: for each operation, you should use the synchronous or
	// asynchronous variant of the client method based on the `use_async_method`
	// setting of the client instance. For starters, you can choose to implement
	// one variant, and return UNIMPLEMENTED status for the other.
	//
	// Reads a row with the client instance.
	// The result row may not be present in the response.
	// Callers should check for it (e.g. calling has_row() in C++).
	ReadRow(context.Context, *ReadRowRequest) (*RowResult, error)
	// Reads rows with the client instance.
	ReadRows(context.Context, *ReadRowsRequest) (*RowsResult, error)
	// Writes a row with the client instance.
	MutateRow(context.Context, *MutateRowRequest) (*MutateRowResult, error)
	// Writes multiple rows with the client instance.
	BulkMutateRows(context.Context, *MutateRowsRequest) (*MutateRowsResult, error)
	// Performs a check-and-mutate-row operation with the client instance.
	CheckAndMutateRow(context.Context, *CheckAndMutateRowRequest) (*CheckAndMutateRowResult, error)
	// Obtains a row key sampling with the client instance.
	SampleRowKeys(context.Context, *SampleRowKeysRequest) (*SampleRowKeysResult, error)
	// Performs a read-modify-write operation with the client.
	ReadModifyWriteRow(context.Context, *ReadModifyWriteRowRequest) (*RowResult, error)
	// Executes a SQL query with the client.
	ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResult, error)
	mustEmbedUnimplementedCloudBigtableV2TestProxyServer()
}

// UnimplementedCloudBigtableV2TestProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudBigtableV2TestProxyServer struct{}

func (UnimplementedCloudBigtableV2TestProxyServer) CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (UnimplementedCloudBigtableV2TestProxyServer) CloseClient(context.Context, *CloseClientRequest) (*CloseClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseClient not implemented")
}
func (UnimplementedCloudBigtableV2TestProxyServer) RemoveClient(context.Context, *RemoveClientRequest) (*RemoveClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveClient not implemented")
}
func (UnimplementedCloudBigtableV2TestProxyServer) ReadRow(context.Context, *ReadRowRequest) (*RowResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadRow not implemented")
}
func (UnimplementedCloudBigtableV2TestProxyServer) ReadRows(context.Context, *ReadRowsRequest) (*RowsResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadRows not implemented")
}
func (UnimplementedCloudBigtableV2TestProxyServer) MutateRow(context.Context, *MutateRowRequest) (*MutateRowResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MutateRow not implemented")
}
func (UnimplementedCloudBigtableV2TestProxyServer) BulkMutateRows(context.Context, *MutateRowsRequest) (*MutateRowsResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkMutateRows not implemented")
}
func (UnimplementedCloudBigtableV2TestProxyServer) CheckAndMutateRow(context.Context, *CheckAndMutateRowRequest) (*CheckAndMutateRowResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAndMutateRow not implemented")
}
func (UnimplementedCloudBigtableV2TestProxyServer) SampleRowKeys(context.Context, *SampleRowKeysRequest) (*SampleRowKeysResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SampleRowKeys not implemented")
}
func (UnimplementedCloudBigtableV2TestProxyServer) ReadModifyWriteRow(context.Context, *ReadModifyWriteRowRequest) (*RowResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadModifyWriteRow not implemented")
}
func (UnimplementedCloudBigtableV2TestProxyServer) ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedCloudBigtableV2TestProxyServer) mustEmbedUnimplementedCloudBigtableV2TestProxyServer() {
}
func (UnimplementedCloudBigtableV2TestProxyServer) testEmbeddedByValue() {}

// UnsafeCloudBigtableV2TestProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudBigtableV2TestProxyServer will
// result in compilation errors.
type UnsafeCloudBigtableV2TestProxyServer interface {
	mustEmbedUnimplementedCloudBigtableV2TestProxyServer()
}

func RegisterCloudBigtableV2TestProxyServer(s grpc.ServiceRegistrar, srv CloudBigtableV2TestProxyServer) {
	// If the following call pancis, it indicates UnimplementedCloudBigtableV2TestProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudBigtableV2TestProxy_ServiceDesc, srv)
}

func _CloudBigtableV2TestProxy_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudBigtableV2TestProxyServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudBigtableV2TestProxy_CreateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudBigtableV2TestProxyServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudBigtableV2TestProxy_CloseClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudBigtableV2TestProxyServer).CloseClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudBigtableV2TestProxy_CloseClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudBigtableV2TestProxyServer).CloseClient(ctx, req.(*CloseClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudBigtableV2TestProxy_RemoveClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudBigtableV2TestProxyServer).RemoveClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudBigtableV2TestProxy_RemoveClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudBigtableV2TestProxyServer).RemoveClient(ctx, req.(*RemoveClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudBigtableV2TestProxy_ReadRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudBigtableV2TestProxyServer).ReadRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudBigtableV2TestProxy_ReadRow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudBigtableV2TestProxyServer).ReadRow(ctx, req.(*ReadRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudBigtableV2TestProxy_ReadRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudBigtableV2TestProxyServer).ReadRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudBigtableV2TestProxy_ReadRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudBigtableV2TestProxyServer).ReadRows(ctx, req.(*ReadRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudBigtableV2TestProxy_MutateRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudBigtableV2TestProxyServer).MutateRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudBigtableV2TestProxy_MutateRow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudBigtableV2TestProxyServer).MutateRow(ctx, req.(*MutateRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudBigtableV2TestProxy_BulkMutateRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudBigtableV2TestProxyServer).BulkMutateRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudBigtableV2TestProxy_BulkMutateRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudBigtableV2TestProxyServer).BulkMutateRows(ctx, req.(*MutateRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudBigtableV2TestProxy_CheckAndMutateRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAndMutateRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudBigtableV2TestProxyServer).CheckAndMutateRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudBigtableV2TestProxy_CheckAndMutateRow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudBigtableV2TestProxyServer).CheckAndMutateRow(ctx, req.(*CheckAndMutateRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudBigtableV2TestProxy_SampleRowKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleRowKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudBigtableV2TestProxyServer).SampleRowKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudBigtableV2TestProxy_SampleRowKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudBigtableV2TestProxyServer).SampleRowKeys(ctx, req.(*SampleRowKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudBigtableV2TestProxy_ReadModifyWriteRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadModifyWriteRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudBigtableV2TestProxyServer).ReadModifyWriteRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudBigtableV2TestProxy_ReadModifyWriteRow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudBigtableV2TestProxyServer).ReadModifyWriteRow(ctx, req.(*ReadModifyWriteRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudBigtableV2TestProxy_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudBigtableV2TestProxyServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudBigtableV2TestProxy_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudBigtableV2TestProxyServer).ExecuteQuery(ctx, req.(*ExecuteQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudBigtableV2TestProxy_ServiceDesc is the grpc.ServiceDesc for CloudBigtableV2TestProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudBigtableV2TestProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.bigtable.testproxy.CloudBigtableV2TestProxy",
	HandlerType: (*CloudBigtableV2TestProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _CloudBigtableV2TestProxy_CreateClient_Handler,
		},
		{
			MethodName: "CloseClient",
			Handler:    _CloudBigtableV2TestProxy_CloseClient_Handler,
		},
		{
			MethodName: "RemoveClient",
			Handler:    _CloudBigtableV2TestProxy_RemoveClient_Handler,
		},
		{
			MethodName: "ReadRow",
			Handler:    _CloudBigtableV2TestProxy_ReadRow_Handler,
		},
		{
			MethodName: "ReadRows",
			Handler:    _CloudBigtableV2TestProxy_ReadRows_Handler,
		},
		{
			MethodName: "MutateRow",
			Handler:    _CloudBigtableV2TestProxy_MutateRow_Handler,
		},
		{
			MethodName: "BulkMutateRows",
			Handler:    _CloudBigtableV2TestProxy_BulkMutateRows_Handler,
		},
		{
			MethodName: "CheckAndMutateRow",
			Handler:    _CloudBigtableV2TestProxy_CheckAndMutateRow_Handler,
		},
		{
			MethodName: "SampleRowKeys",
			Handler:    _CloudBigtableV2TestProxy_SampleRowKeys_Handler,
		},
		{
			MethodName: "ReadModifyWriteRow",
			Handler:    _CloudBigtableV2TestProxy_ReadModifyWriteRow_Handler,
		},
		{
			MethodName: "ExecuteQuery",
			Handler:    _CloudBigtableV2TestProxy_ExecuteQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test_proxy.proto",
}
