// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: test_proxy.proto

package testproxypb

import (
	bigtablepb "cloud.google.com/go/bigtable/apiv2/bigtablepb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A config flag that dictates how the optional features should be enabled
// during the client creation. The optional features customize how the client
// interacts with the server, and are defined in
// https://github.com/googleapis/googleapis/blob/master/google/bigtable/v2/feature_flags.proto
type OptionalFeatureConfig int32

const (
	OptionalFeatureConfig_OPTIONAL_FEATURE_CONFIG_DEFAULT    OptionalFeatureConfig = 0
	OptionalFeatureConfig_OPTIONAL_FEATURE_CONFIG_ENABLE_ALL OptionalFeatureConfig = 1
)

// Enum value maps for OptionalFeatureConfig.
var (
	OptionalFeatureConfig_name = map[int32]string{
		0: "OPTIONAL_FEATURE_CONFIG_DEFAULT",
		1: "OPTIONAL_FEATURE_CONFIG_ENABLE_ALL",
	}
	OptionalFeatureConfig_value = map[string]int32{
		"OPTIONAL_FEATURE_CONFIG_DEFAULT":    0,
		"OPTIONAL_FEATURE_CONFIG_ENABLE_ALL": 1,
	}
)

func (x OptionalFeatureConfig) Enum() *OptionalFeatureConfig {
	p := new(OptionalFeatureConfig)
	*p = x
	return p
}

func (x OptionalFeatureConfig) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptionalFeatureConfig) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proxy_proto_enumTypes[0].Descriptor()
}

func (OptionalFeatureConfig) Type() protoreflect.EnumType {
	return &file_test_proxy_proto_enumTypes[0]
}

func (x OptionalFeatureConfig) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptionalFeatureConfig.Descriptor instead.
func (OptionalFeatureConfig) EnumDescriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{0}
}

// Request to test proxy service to create a client object.
type CreateClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique ID associated with the client object to be created.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The "host:port" address of the data API endpoint (i.e. the backend being
	// proxied to). Example: 127.0.0.1:38543. If you want to connect to a local
	// emulator via BIGTABLE_EMULATOR_HOST environment variable, you can use
	// "emulator" instead of "host:port" for this field.
	DataTarget string `protobuf:"bytes,2,opt,name=data_target,json=dataTarget,proto3" json:"data_target,omitempty"`
	// The project for all calls on this client.
	ProjectId string `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The instance for all calls on this client.
	InstanceId string `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Optional app profile for all calls on this client.
	// Some client bindings allow specifying the app profile on a per-operation
	// basis. We don't yet support this in the proxy API, but may in the future.
	AppProfileId string `protobuf:"bytes,5,opt,name=app_profile_id,json=appProfileId,proto3" json:"app_profile_id,omitempty"`
	// If provided, a custom timeout will be set for each API call conducted by
	// the created client. Otherwise, the default timeout from the client library
	// will be used. Note that the override applies to all the methods.
	PerOperationTimeout *durationpb.Duration `protobuf:"bytes,6,opt,name=per_operation_timeout,json=perOperationTimeout,proto3" json:"per_operation_timeout,omitempty"`
	// Optional config that dictates how the optional features should be enabled
	// during the client creation. Please check the enum type's docstring above.
	OptionalFeatureConfig OptionalFeatureConfig `protobuf:"varint,7,opt,name=optional_feature_config,json=optionalFeatureConfig,proto3,enum=google.bigtable.testproxy.OptionalFeatureConfig" json:"optional_feature_config,omitempty"`
	// Options to allow connecting to backends with channel and/or call
	// credentials. This is needed internally by Cloud Bigtable's own testing
	// frameworks.It is not necessary to support these fields for client
	// conformance testing.
	//
	// WARNING: this allows the proxy to connect to a real production
	// CBT backend with the right options, however, the proxy itself is insecure
	// so it is not recommended to use it with real credentials or outside testing
	// contexts.
	SecurityOptions *CreateClientRequest_SecurityOptions `protobuf:"bytes,8,opt,name=security_options,json=securityOptions,proto3" json:"security_options,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_test_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateClientRequest) GetDataTarget() string {
	if x != nil {
		return x.DataTarget
	}
	return ""
}

func (x *CreateClientRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateClientRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateClientRequest) GetAppProfileId() string {
	if x != nil {
		return x.AppProfileId
	}
	return ""
}

func (x *CreateClientRequest) GetPerOperationTimeout() *durationpb.Duration {
	if x != nil {
		return x.PerOperationTimeout
	}
	return nil
}

func (x *CreateClientRequest) GetOptionalFeatureConfig() OptionalFeatureConfig {
	if x != nil {
		return x.OptionalFeatureConfig
	}
	return OptionalFeatureConfig_OPTIONAL_FEATURE_CONFIG_DEFAULT
}

func (x *CreateClientRequest) GetSecurityOptions() *CreateClientRequest_SecurityOptions {
	if x != nil {
		return x.SecurityOptions
	}
	return nil
}

// Response from test proxy service for CreateClientRequest.
type CreateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
	mi := &file_test_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientResponse.ProtoReflect.Descriptor instead.
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{1}
}

// Request to test proxy service to close a client object.
type CloseClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the target client object.
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseClientRequest) Reset() {
	*x = CloseClientRequest{}
	mi := &file_test_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseClientRequest) ProtoMessage() {}

func (x *CloseClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseClientRequest.ProtoReflect.Descriptor instead.
func (*CloseClientRequest) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *CloseClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Response from test proxy service for CloseClientRequest.
type CloseClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseClientResponse) Reset() {
	*x = CloseClientResponse{}
	mi := &file_test_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseClientResponse) ProtoMessage() {}

func (x *CloseClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseClientResponse.ProtoReflect.Descriptor instead.
func (*CloseClientResponse) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{3}
}

// Request to test proxy service to remove a client object.
type RemoveClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the target client object.
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveClientRequest) Reset() {
	*x = RemoveClientRequest{}
	mi := &file_test_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveClientRequest) ProtoMessage() {}

func (x *RemoveClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveClientRequest.ProtoReflect.Descriptor instead.
func (*RemoveClientRequest) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Response from test proxy service for RemoveClientRequest.
type RemoveClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveClientResponse) Reset() {
	*x = RemoveClientResponse{}
	mi := &file_test_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveClientResponse) ProtoMessage() {}

func (x *RemoveClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveClientResponse.ProtoReflect.Descriptor instead.
func (*RemoveClientResponse) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{5}
}

// Request to test proxy service to read a row.
type ReadRowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the target client object.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The unique name of the table from which to read the row.
	// Values are of the form
	// `projects/<project>/instances/<instance>/tables/<table>`.
	TableName string `protobuf:"bytes,4,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// The row key of the target row.
	RowKey string `protobuf:"bytes,2,opt,name=row_key,json=rowKey,proto3" json:"row_key,omitempty"`
	// The row filter to be applied to the target row.
	Filter        *bigtablepb.RowFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRowRequest) Reset() {
	*x = ReadRowRequest{}
	mi := &file_test_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRowRequest) ProtoMessage() {}

func (x *ReadRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRowRequest.ProtoReflect.Descriptor instead.
func (*ReadRowRequest) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *ReadRowRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReadRowRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ReadRowRequest) GetRowKey() string {
	if x != nil {
		return x.RowKey
	}
	return ""
}

func (x *ReadRowRequest) GetFilter() *bigtablepb.RowFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response from test proxy service for ReadRowRequest or
// ReadModifyWriteRowRequest.
type RowResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RPC status from the client binding.
	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// The contents of a single row.
	Row           *bigtablepb.Row `protobuf:"bytes,2,opt,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowResult) Reset() {
	*x = RowResult{}
	mi := &file_test_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowResult) ProtoMessage() {}

func (x *RowResult) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowResult.ProtoReflect.Descriptor instead.
func (*RowResult) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *RowResult) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RowResult) GetRow() *bigtablepb.Row {
	if x != nil {
		return x.Row
	}
	return nil
}

// Request to test proxy service to read rows.
type ReadRowsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the target client object.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The raw request to the Bigtable server.
	Request *bigtablepb.ReadRowsRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	// The streaming read can be canceled before all items are seen.
	// Has no effect if non-positive.
	CancelAfterRows int32 `protobuf:"varint,3,opt,name=cancel_after_rows,json=cancelAfterRows,proto3" json:"cancel_after_rows,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadRowsRequest) Reset() {
	*x = ReadRowsRequest{}
	mi := &file_test_proxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRowsRequest) ProtoMessage() {}

func (x *ReadRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRowsRequest.ProtoReflect.Descriptor instead.
func (*ReadRowsRequest) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *ReadRowsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReadRowsRequest) GetRequest() *bigtablepb.ReadRowsRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ReadRowsRequest) GetCancelAfterRows() int32 {
	if x != nil {
		return x.CancelAfterRows
	}
	return 0
}

// Response from test proxy service for ReadRowsRequest.
type RowsResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RPC status from the client binding.
	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// The contents of rows.
	Rows          []*bigtablepb.Row `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowsResult) Reset() {
	*x = RowsResult{}
	mi := &file_test_proxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowsResult) ProtoMessage() {}

func (x *RowsResult) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowsResult.ProtoReflect.Descriptor instead.
func (*RowsResult) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{9}
}

func (x *RowsResult) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RowsResult) GetRows() []*bigtablepb.Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

// Request to test proxy service to mutate a row.
type MutateRowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the target client object.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The raw request to the Bigtable server.
	Request       *bigtablepb.MutateRowRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateRowRequest) Reset() {
	*x = MutateRowRequest{}
	mi := &file_test_proxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateRowRequest) ProtoMessage() {}

func (x *MutateRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateRowRequest.ProtoReflect.Descriptor instead.
func (*MutateRowRequest) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{10}
}

func (x *MutateRowRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MutateRowRequest) GetRequest() *bigtablepb.MutateRowRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// Response from test proxy service for MutateRowRequest.
type MutateRowResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RPC status from the client binding.
	Status        *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateRowResult) Reset() {
	*x = MutateRowResult{}
	mi := &file_test_proxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateRowResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateRowResult) ProtoMessage() {}

func (x *MutateRowResult) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateRowResult.ProtoReflect.Descriptor instead.
func (*MutateRowResult) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{11}
}

func (x *MutateRowResult) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// Request to test proxy service to mutate rows.
type MutateRowsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the target client object.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The raw request to the Bigtable server.
	Request       *bigtablepb.MutateRowsRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateRowsRequest) Reset() {
	*x = MutateRowsRequest{}
	mi := &file_test_proxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateRowsRequest) ProtoMessage() {}

func (x *MutateRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateRowsRequest.ProtoReflect.Descriptor instead.
func (*MutateRowsRequest) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{12}
}

func (x *MutateRowsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MutateRowsRequest) GetRequest() *bigtablepb.MutateRowsRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// Response from test proxy service for MutateRowsRequest.
type MutateRowsResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RPC status from the client binding, corresponding to the
	// whole operation.
	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// The results corresponding to the failed rows.
	Entries       []*bigtablepb.MutateRowsResponse_Entry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateRowsResult) Reset() {
	*x = MutateRowsResult{}
	mi := &file_test_proxy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateRowsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateRowsResult) ProtoMessage() {}

func (x *MutateRowsResult) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateRowsResult.ProtoReflect.Descriptor instead.
func (*MutateRowsResult) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{13}
}

func (x *MutateRowsResult) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *MutateRowsResult) GetEntries() []*bigtablepb.MutateRowsResponse_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Request to test proxy service to check and mutate a row.
type CheckAndMutateRowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the target client object.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The raw request to the Bigtable server.
	Request       *bigtablepb.CheckAndMutateRowRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAndMutateRowRequest) Reset() {
	*x = CheckAndMutateRowRequest{}
	mi := &file_test_proxy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAndMutateRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndMutateRowRequest) ProtoMessage() {}

func (x *CheckAndMutateRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndMutateRowRequest.ProtoReflect.Descriptor instead.
func (*CheckAndMutateRowRequest) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{14}
}

func (x *CheckAndMutateRowRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CheckAndMutateRowRequest) GetRequest() *bigtablepb.CheckAndMutateRowRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// Response from test proxy service for CheckAndMutateRowRequest.
type CheckAndMutateRowResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RPC status from the client binding.
	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// The raw response from the Bigtable server.
	Result        *bigtablepb.CheckAndMutateRowResponse `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAndMutateRowResult) Reset() {
	*x = CheckAndMutateRowResult{}
	mi := &file_test_proxy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAndMutateRowResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndMutateRowResult) ProtoMessage() {}

func (x *CheckAndMutateRowResult) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndMutateRowResult.ProtoReflect.Descriptor instead.
func (*CheckAndMutateRowResult) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{15}
}

func (x *CheckAndMutateRowResult) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CheckAndMutateRowResult) GetResult() *bigtablepb.CheckAndMutateRowResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

// Request to test proxy service to sample row keys.
type SampleRowKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the target client object.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The raw request to the Bigtable server.
	Request       *bigtablepb.SampleRowKeysRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleRowKeysRequest) Reset() {
	*x = SampleRowKeysRequest{}
	mi := &file_test_proxy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleRowKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleRowKeysRequest) ProtoMessage() {}

func (x *SampleRowKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleRowKeysRequest.ProtoReflect.Descriptor instead.
func (*SampleRowKeysRequest) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{16}
}

func (x *SampleRowKeysRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SampleRowKeysRequest) GetRequest() *bigtablepb.SampleRowKeysRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// Response from test proxy service for SampleRowKeysRequest.
type SampleRowKeysResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RPC status from the client binding.
	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// The raw responses from the Bigtable server.
	Samples       []*bigtablepb.SampleRowKeysResponse `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleRowKeysResult) Reset() {
	*x = SampleRowKeysResult{}
	mi := &file_test_proxy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleRowKeysResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleRowKeysResult) ProtoMessage() {}

func (x *SampleRowKeysResult) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleRowKeysResult.ProtoReflect.Descriptor instead.
func (*SampleRowKeysResult) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{17}
}

func (x *SampleRowKeysResult) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SampleRowKeysResult) GetSamples() []*bigtablepb.SampleRowKeysResponse {
	if x != nil {
		return x.Samples
	}
	return nil
}

// Request to test proxy service to read modify write a row.
type ReadModifyWriteRowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the target client object.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The raw request to the Bigtable server.
	Request       *bigtablepb.ReadModifyWriteRowRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadModifyWriteRowRequest) Reset() {
	*x = ReadModifyWriteRowRequest{}
	mi := &file_test_proxy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadModifyWriteRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadModifyWriteRowRequest) ProtoMessage() {}

func (x *ReadModifyWriteRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadModifyWriteRowRequest.ProtoReflect.Descriptor instead.
func (*ReadModifyWriteRowRequest) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{18}
}

func (x *ReadModifyWriteRowRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReadModifyWriteRowRequest) GetRequest() *bigtablepb.ReadModifyWriteRowRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// Request to test proxy service to execute a query.
type ExecuteQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the target client object.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The raw request to the Bigtable server.
	Request *bigtablepb.ExecuteQueryRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	// A collection of proto descriptor files for deserializing PROTO/ENUM columns
	// in the query result. The descriptor files must be provided in dependency
	// order.
	FileDescriptorSet *descriptorpb.FileDescriptorSet `protobuf:"bytes,3,opt,name=file_descriptor_set,json=fileDescriptorSet,proto3" json:"file_descriptor_set,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_test_proxy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{19}
}

func (x *ExecuteQueryRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ExecuteQueryRequest) GetRequest() *bigtablepb.ExecuteQueryRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExecuteQueryRequest) GetFileDescriptorSet() *descriptorpb.FileDescriptorSet {
	if x != nil {
		return x.FileDescriptorSet
	}
	return nil
}

// Response from test proxy service for ExecuteQueryRequest.
type ExecuteQueryResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RPC status from the client binding.
	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Name and type information for the query result.
	Metadata *ResultSetMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Encoded version of the ResultSet. Should not contain type information.
	Rows          []*SqlRow `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryResult) Reset() {
	*x = ExecuteQueryResult{}
	mi := &file_test_proxy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResult) ProtoMessage() {}

func (x *ExecuteQueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryResult.ProtoReflect.Descriptor instead.
func (*ExecuteQueryResult) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{20}
}

func (x *ExecuteQueryResult) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ExecuteQueryResult) GetMetadata() *ResultSetMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteQueryResult) GetRows() []*SqlRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

// Schema information for the query result.
type ResultSetMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column metadata for each column inthe query result.
	Columns       []*bigtablepb.ColumnMetadata `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultSetMetadata) Reset() {
	*x = ResultSetMetadata{}
	mi := &file_test_proxy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultSetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultSetMetadata) ProtoMessage() {}

func (x *ResultSetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultSetMetadata.ProtoReflect.Descriptor instead.
func (*ResultSetMetadata) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{21}
}

func (x *ResultSetMetadata) GetColumns() []*bigtablepb.ColumnMetadata {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Representation of a single row in the query result.
type SqlRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Columnar values returned by the query.
	Values        []*bigtablepb.Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlRow) Reset() {
	*x = SqlRow{}
	mi := &file_test_proxy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlRow) ProtoMessage() {}

func (x *SqlRow) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlRow.ProtoReflect.Descriptor instead.
func (*SqlRow) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{22}
}

func (x *SqlRow) GetValues() []*bigtablepb.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type CreateClientRequest_SecurityOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Access token to use for client credentials. If empty, the client will not
	// use any call credentials. Certain implementations may require `use_ssl`
	// to be set when using this.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Whether to use SSL channel credentials when connecting to the data
	// endpoint.
	UseSsl bool `protobuf:"varint,2,opt,name=use_ssl,json=useSsl,proto3" json:"use_ssl,omitempty"`
	// If using SSL channel credentials, override the SSL endpoint to match the
	// host that is specified in the backend's certificate. Also sets the
	// client's authority header value.
	SslEndpointOverride string `protobuf:"bytes,3,opt,name=ssl_endpoint_override,json=sslEndpointOverride,proto3" json:"ssl_endpoint_override,omitempty"`
	// PEM encoding of the server root certificates. If not set, the default
	// root certs will be used instead. The default can be overridden via the
	// GRPC_DEFAULT_SSL_ROOTS_FILE_PATH env var.
	SslRootCertsPem string `protobuf:"bytes,4,opt,name=ssl_root_certs_pem,json=sslRootCertsPem,proto3" json:"ssl_root_certs_pem,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateClientRequest_SecurityOptions) Reset() {
	*x = CreateClientRequest_SecurityOptions{}
	mi := &file_test_proxy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest_SecurityOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest_SecurityOptions) ProtoMessage() {}

func (x *CreateClientRequest_SecurityOptions) ProtoReflect() protoreflect.Message {
	mi := &file_test_proxy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest_SecurityOptions.ProtoReflect.Descriptor instead.
func (*CreateClientRequest_SecurityOptions) Descriptor() ([]byte, []int) {
	return file_test_proxy_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateClientRequest_SecurityOptions) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CreateClientRequest_SecurityOptions) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

func (x *CreateClientRequest_SecurityOptions) GetSslEndpointOverride() string {
	if x != nil {
		return x.SslEndpointOverride
	}
	return ""
}

func (x *CreateClientRequest_SecurityOptions) GetSslRootCertsPem() string {
	if x != nil {
		return x.SslRootCertsPem
	}
	return ""
}

var File_test_proxy_proto protoreflect.FileDescriptor

const file_test_proxy_proto_rawDesc = "" +
	"\n" +
	"\x10test_proxy.proto\x12\x19google.bigtable.testproxy\x1a\x17google/api/client.proto\x1a!google/bigtable/v2/bigtable.proto\x1a\x1dgoogle/bigtable/v2/data.proto\x1a google/protobuf/descriptor.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x17google/rpc/status.proto\"\x8e\x05\n" +
	"\x13CreateClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vdata_target\x18\x02 \x01(\tR\n" +
	"dataTarget\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId\x12$\n" +
	"\x0eapp_profile_id\x18\x05 \x01(\tR\fappProfileId\x12M\n" +
	"\x15per_operation_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x13perOperationTimeout\x12h\n" +
	"\x17optional_feature_config\x18\a \x01(\x0e20.google.bigtable.testproxy.OptionalFeatureConfigR\x15optionalFeatureConfig\x12i\n" +
	"\x10security_options\x18\b \x01(\v2>.google.bigtable.testproxy.CreateClientRequest.SecurityOptionsR\x0fsecurityOptions\x1a\xae\x01\n" +
	"\x0fSecurityOptions\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x17\n" +
	"\ause_ssl\x18\x02 \x01(\bR\x06useSsl\x122\n" +
	"\x15ssl_endpoint_override\x18\x03 \x01(\tR\x13sslEndpointOverride\x12+\n" +
	"\x12ssl_root_certs_pem\x18\x04 \x01(\tR\x0fsslRootCertsPem\"\x16\n" +
	"\x14CreateClientResponse\"1\n" +
	"\x12CloseClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\x15\n" +
	"\x13CloseClientResponse\"2\n" +
	"\x13RemoveClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\x16\n" +
	"\x14RemoveClientResponse\"\x9c\x01\n" +
	"\x0eReadRowRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"table_name\x18\x04 \x01(\tR\ttableName\x12\x17\n" +
	"\arow_key\x18\x02 \x01(\tR\x06rowKey\x125\n" +
	"\x06filter\x18\x03 \x01(\v2\x1d.google.bigtable.v2.RowFilterR\x06filter\"b\n" +
	"\tRowResult\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12)\n" +
	"\x03row\x18\x02 \x01(\v2\x17.google.bigtable.v2.RowR\x03row\"\x99\x01\n" +
	"\x0fReadRowsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12=\n" +
	"\arequest\x18\x02 \x01(\v2#.google.bigtable.v2.ReadRowsRequestR\arequest\x12*\n" +
	"\x11cancel_after_rows\x18\x03 \x01(\x05R\x0fcancelAfterRows\"e\n" +
	"\n" +
	"RowsResult\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12+\n" +
	"\x04rows\x18\x02 \x03(\v2\x17.google.bigtable.v2.RowR\x04rows\"o\n" +
	"\x10MutateRowRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12>\n" +
	"\arequest\x18\x02 \x01(\v2$.google.bigtable.v2.MutateRowRequestR\arequest\"=\n" +
	"\x0fMutateRowResult\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\"q\n" +
	"\x11MutateRowsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12?\n" +
	"\arequest\x18\x02 \x01(\v2%.google.bigtable.v2.MutateRowsRequestR\arequest\"\x86\x01\n" +
	"\x10MutateRowsResult\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12F\n" +
	"\aentries\x18\x02 \x03(\v2,.google.bigtable.v2.MutateRowsResponse.EntryR\aentries\"\x7f\n" +
	"\x18CheckAndMutateRowRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12F\n" +
	"\arequest\x18\x02 \x01(\v2,.google.bigtable.v2.CheckAndMutateRowRequestR\arequest\"\x8c\x01\n" +
	"\x17CheckAndMutateRowResult\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12E\n" +
	"\x06result\x18\x02 \x01(\v2-.google.bigtable.v2.CheckAndMutateRowResponseR\x06result\"w\n" +
	"\x14SampleRowKeysRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12B\n" +
	"\arequest\x18\x02 \x01(\v2(.google.bigtable.v2.SampleRowKeysRequestR\arequest\"\x86\x01\n" +
	"\x13SampleRowKeysResult\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12C\n" +
	"\asamples\x18\x02 \x03(\v2).google.bigtable.v2.SampleRowKeysResponseR\asamples\"\x81\x01\n" +
	"\x19ReadModifyWriteRowRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12G\n" +
	"\arequest\x18\x02 \x01(\v2-.google.bigtable.v2.ReadModifyWriteRowRequestR\arequest\"\xc9\x01\n" +
	"\x13ExecuteQueryRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12A\n" +
	"\arequest\x18\x02 \x01(\v2'.google.bigtable.v2.ExecuteQueryRequestR\arequest\x12R\n" +
	"\x13file_descriptor_set\x18\x03 \x01(\v2\".google.protobuf.FileDescriptorSetR\x11fileDescriptorSet\"\xc1\x01\n" +
	"\x12ExecuteQueryResult\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12H\n" +
	"\bmetadata\x18\x04 \x01(\v2,.google.bigtable.testproxy.ResultSetMetadataR\bmetadata\x125\n" +
	"\x04rows\x18\x03 \x03(\v2!.google.bigtable.testproxy.SqlRowR\x04rows\"Q\n" +
	"\x11ResultSetMetadata\x12<\n" +
	"\acolumns\x18\x01 \x03(\v2\".google.bigtable.v2.ColumnMetadataR\acolumns\";\n" +
	"\x06SqlRow\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.google.bigtable.v2.ValueR\x06values*d\n" +
	"\x15OptionalFeatureConfig\x12#\n" +
	"\x1fOPTIONAL_FEATURE_CONFIG_DEFAULT\x10\x00\x12&\n" +
	"\"OPTIONAL_FEATURE_CONFIG_ENABLE_ALL\x10\x012\x95\n" +
	"\n" +
	"\x18CloudBigtableV2TestProxy\x12q\n" +
	"\fCreateClient\x12..google.bigtable.testproxy.CreateClientRequest\x1a/.google.bigtable.testproxy.CreateClientResponse\"\x00\x12n\n" +
	"\vCloseClient\x12-.google.bigtable.testproxy.CloseClientRequest\x1a..google.bigtable.testproxy.CloseClientResponse\"\x00\x12q\n" +
	"\fRemoveClient\x12..google.bigtable.testproxy.RemoveClientRequest\x1a/.google.bigtable.testproxy.RemoveClientResponse\"\x00\x12\\\n" +
	"\aReadRow\x12).google.bigtable.testproxy.ReadRowRequest\x1a$.google.bigtable.testproxy.RowResult\"\x00\x12_\n" +
	"\bReadRows\x12*.google.bigtable.testproxy.ReadRowsRequest\x1a%.google.bigtable.testproxy.RowsResult\"\x00\x12f\n" +
	"\tMutateRow\x12+.google.bigtable.testproxy.MutateRowRequest\x1a*.google.bigtable.testproxy.MutateRowResult\"\x00\x12m\n" +
	"\x0eBulkMutateRows\x12,.google.bigtable.testproxy.MutateRowsRequest\x1a+.google.bigtable.testproxy.MutateRowsResult\"\x00\x12~\n" +
	"\x11CheckAndMutateRow\x123.google.bigtable.testproxy.CheckAndMutateRowRequest\x1a2.google.bigtable.testproxy.CheckAndMutateRowResult\"\x00\x12r\n" +
	"\rSampleRowKeys\x12/.google.bigtable.testproxy.SampleRowKeysRequest\x1a..google.bigtable.testproxy.SampleRowKeysResult\"\x00\x12r\n" +
	"\x12ReadModifyWriteRow\x124.google.bigtable.testproxy.ReadModifyWriteRowRequest\x1a$.google.bigtable.testproxy.RowResult\"\x00\x12o\n" +
	"\fExecuteQuery\x12..google.bigtable.testproxy.ExecuteQueryRequest\x1a-.google.bigtable.testproxy.ExecuteQueryResult\"\x00\x1a4\xcaA1bigtable-test-proxy-not-accessible.googleapis.comBg\n" +
	"#com.google.cloud.bigtable.testproxyP\x01Z>cloud.google.com/go/bigtable/testproxy/testproxypb;testproxypbb\x06proto3"

var (
	file_test_proxy_proto_rawDescOnce sync.Once
	file_test_proxy_proto_rawDescData []byte
)

func file_test_proxy_proto_rawDescGZIP() []byte {
	file_test_proxy_proto_rawDescOnce.Do(func() {
		file_test_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proxy_proto_rawDesc), len(file_test_proxy_proto_rawDesc)))
	})
	return file_test_proxy_proto_rawDescData
}

var file_test_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_test_proxy_proto_goTypes = []any{
	(OptionalFeatureConfig)(0),                   // 0: google.bigtable.testproxy.OptionalFeatureConfig
	(*CreateClientRequest)(nil),                  // 1: google.bigtable.testproxy.CreateClientRequest
	(*CreateClientResponse)(nil),                 // 2: google.bigtable.testproxy.CreateClientResponse
	(*CloseClientRequest)(nil),                   // 3: google.bigtable.testproxy.CloseClientRequest
	(*CloseClientResponse)(nil),                  // 4: google.bigtable.testproxy.CloseClientResponse
	(*RemoveClientRequest)(nil),                  // 5: google.bigtable.testproxy.RemoveClientRequest
	(*RemoveClientResponse)(nil),                 // 6: google.bigtable.testproxy.RemoveClientResponse
	(*ReadRowRequest)(nil),                       // 7: google.bigtable.testproxy.ReadRowRequest
	(*RowResult)(nil),                            // 8: google.bigtable.testproxy.RowResult
	(*ReadRowsRequest)(nil),                      // 9: google.bigtable.testproxy.ReadRowsRequest
	(*RowsResult)(nil),                           // 10: google.bigtable.testproxy.RowsResult
	(*MutateRowRequest)(nil),                     // 11: google.bigtable.testproxy.MutateRowRequest
	(*MutateRowResult)(nil),                      // 12: google.bigtable.testproxy.MutateRowResult
	(*MutateRowsRequest)(nil),                    // 13: google.bigtable.testproxy.MutateRowsRequest
	(*MutateRowsResult)(nil),                     // 14: google.bigtable.testproxy.MutateRowsResult
	(*CheckAndMutateRowRequest)(nil),             // 15: google.bigtable.testproxy.CheckAndMutateRowRequest
	(*CheckAndMutateRowResult)(nil),              // 16: google.bigtable.testproxy.CheckAndMutateRowResult
	(*SampleRowKeysRequest)(nil),                 // 17: google.bigtable.testproxy.SampleRowKeysRequest
	(*SampleRowKeysResult)(nil),                  // 18: google.bigtable.testproxy.SampleRowKeysResult
	(*ReadModifyWriteRowRequest)(nil),            // 19: google.bigtable.testproxy.ReadModifyWriteRowRequest
	(*ExecuteQueryRequest)(nil),                  // 20: google.bigtable.testproxy.ExecuteQueryRequest
	(*ExecuteQueryResult)(nil),                   // 21: google.bigtable.testproxy.ExecuteQueryResult
	(*ResultSetMetadata)(nil),                    // 22: google.bigtable.testproxy.ResultSetMetadata
	(*SqlRow)(nil),                               // 23: google.bigtable.testproxy.SqlRow
	(*CreateClientRequest_SecurityOptions)(nil),  // 24: google.bigtable.testproxy.CreateClientRequest.SecurityOptions
	(*durationpb.Duration)(nil),                  // 25: google.protobuf.Duration
	(*bigtablepb.RowFilter)(nil),                 // 26: google.bigtable.v2.RowFilter
	(*status.Status)(nil),                        // 27: google.rpc.Status
	(*bigtablepb.Row)(nil),                       // 28: google.bigtable.v2.Row
	(*bigtablepb.ReadRowsRequest)(nil),           // 29: google.bigtable.v2.ReadRowsRequest
	(*bigtablepb.MutateRowRequest)(nil),          // 30: google.bigtable.v2.MutateRowRequest
	(*bigtablepb.MutateRowsRequest)(nil),         // 31: google.bigtable.v2.MutateRowsRequest
	(*bigtablepb.MutateRowsResponse_Entry)(nil),  // 32: google.bigtable.v2.MutateRowsResponse.Entry
	(*bigtablepb.CheckAndMutateRowRequest)(nil),  // 33: google.bigtable.v2.CheckAndMutateRowRequest
	(*bigtablepb.CheckAndMutateRowResponse)(nil), // 34: google.bigtable.v2.CheckAndMutateRowResponse
	(*bigtablepb.SampleRowKeysRequest)(nil),      // 35: google.bigtable.v2.SampleRowKeysRequest
	(*bigtablepb.SampleRowKeysResponse)(nil),     // 36: google.bigtable.v2.SampleRowKeysResponse
	(*bigtablepb.ReadModifyWriteRowRequest)(nil), // 37: google.bigtable.v2.ReadModifyWriteRowRequest
	(*bigtablepb.ExecuteQueryRequest)(nil),       // 38: google.bigtable.v2.ExecuteQueryRequest
	(*descriptorpb.FileDescriptorSet)(nil),       // 39: google.protobuf.FileDescriptorSet
	(*bigtablepb.ColumnMetadata)(nil),            // 40: google.bigtable.v2.ColumnMetadata
	(*bigtablepb.Value)(nil),                     // 41: google.bigtable.v2.Value
}
var file_test_proxy_proto_depIdxs = []int32{
	25, // 0: google.bigtable.testproxy.CreateClientRequest.per_operation_timeout:type_name -> google.protobuf.Duration
	0,  // 1: google.bigtable.testproxy.CreateClientRequest.optional_feature_config:type_name -> google.bigtable.testproxy.OptionalFeatureConfig
	24, // 2: google.bigtable.testproxy.CreateClientRequest.security_options:type_name -> google.bigtable.testproxy.CreateClientRequest.SecurityOptions
	26, // 3: google.bigtable.testproxy.ReadRowRequest.filter:type_name -> google.bigtable.v2.RowFilter
	27, // 4: google.bigtable.testproxy.RowResult.status:type_name -> google.rpc.Status
	28, // 5: google.bigtable.testproxy.RowResult.row:type_name -> google.bigtable.v2.Row
	29, // 6: google.bigtable.testproxy.ReadRowsRequest.request:type_name -> google.bigtable.v2.ReadRowsRequest
	27, // 7: google.bigtable.testproxy.RowsResult.status:type_name -> google.rpc.Status
	28, // 8: google.bigtable.testproxy.RowsResult.rows:type_name -> google.bigtable.v2.Row
	30, // 9: google.bigtable.testproxy.MutateRowRequest.request:type_name -> google.bigtable.v2.MutateRowRequest
	27, // 10: google.bigtable.testproxy.MutateRowResult.status:type_name -> google.rpc.Status
	31, // 11: google.bigtable.testproxy.MutateRowsRequest.request:type_name -> google.bigtable.v2.MutateRowsRequest
	27, // 12: google.bigtable.testproxy.MutateRowsResult.status:type_name -> google.rpc.Status
	32, // 13: google.bigtable.testproxy.MutateRowsResult.entries:type_name -> google.bigtable.v2.MutateRowsResponse.Entry
	33, // 14: google.bigtable.testproxy.CheckAndMutateRowRequest.request:type_name -> google.bigtable.v2.CheckAndMutateRowRequest
	27, // 15: google.bigtable.testproxy.CheckAndMutateRowResult.status:type_name -> google.rpc.Status
	34, // 16: google.bigtable.testproxy.CheckAndMutateRowResult.result:type_name -> google.bigtable.v2.CheckAndMutateRowResponse
	35, // 17: google.bigtable.testproxy.SampleRowKeysRequest.request:type_name -> google.bigtable.v2.SampleRowKeysRequest
	27, // 18: google.bigtable.testproxy.SampleRowKeysResult.status:type_name -> google.rpc.Status
	36, // 19: google.bigtable.testproxy.SampleRowKeysResult.samples:type_name -> google.bigtable.v2.SampleRowKeysResponse
	37, // 20: google.bigtable.testproxy.ReadModifyWriteRowRequest.request:type_name -> google.bigtable.v2.ReadModifyWriteRowRequest
	38, // 21: google.bigtable.testproxy.ExecuteQueryRequest.request:type_name -> google.bigtable.v2.ExecuteQueryRequest
	39, // 22: google.bigtable.testproxy.ExecuteQueryRequest.file_descriptor_set:type_name -> google.protobuf.FileDescriptorSet
	27, // 23: google.bigtable.testproxy.ExecuteQueryResult.status:type_name -> google.rpc.Status
	22, // 24: google.bigtable.testproxy.ExecuteQueryResult.metadata:type_name -> google.bigtable.testproxy.ResultSetMetadata
	23, // 25: google.bigtable.testproxy.ExecuteQueryResult.rows:type_name -> google.bigtable.testproxy.SqlRow
	40, // 26: google.bigtable.testproxy.ResultSetMetadata.columns:type_name -> google.bigtable.v2.ColumnMetadata
	41, // 27: google.bigtable.testproxy.SqlRow.values:type_name -> google.bigtable.v2.Value
	1,  // 28: google.bigtable.testproxy.CloudBigtableV2TestProxy.CreateClient:input_type -> google.bigtable.testproxy.CreateClientRequest
	3,  // 29: google.bigtable.testproxy.CloudBigtableV2TestProxy.CloseClient:input_type -> google.bigtable.testproxy.CloseClientRequest
	5,  // 30: google.bigtable.testproxy.CloudBigtableV2TestProxy.RemoveClient:input_type -> google.bigtable.testproxy.RemoveClientRequest
	7,  // 31: google.bigtable.testproxy.CloudBigtableV2TestProxy.ReadRow:input_type -> google.bigtable.testproxy.ReadRowRequest
	9,  // 32: google.bigtable.testproxy.CloudBigtableV2TestProxy.ReadRows:input_type -> google.bigtable.testproxy.ReadRowsRequest
	11, // 33: google.bigtable.testproxy.CloudBigtableV2TestProxy.MutateRow:input_type -> google.bigtable.testproxy.MutateRowRequest
	13, // 34: google.bigtable.testproxy.CloudBigtableV2TestProxy.BulkMutateRows:input_type -> google.bigtable.testproxy.MutateRowsRequest
	15, // 35: google.bigtable.testproxy.CloudBigtableV2TestProxy.CheckAndMutateRow:input_type -> google.bigtable.testproxy.CheckAndMutateRowRequest
	17, // 36: google.bigtable.testproxy.CloudBigtableV2TestProxy.SampleRowKeys:input_type -> google.bigtable.testproxy.SampleRowKeysRequest
	19, // 37: google.bigtable.testproxy.CloudBigtableV2TestProxy.ReadModifyWriteRow:input_type -> google.bigtable.testproxy.ReadModifyWriteRowRequest
	20, // 38: google.bigtable.testproxy.CloudBigtableV2TestProxy.ExecuteQuery:input_type -> google.bigtable.testproxy.ExecuteQueryRequest
	2,  // 39: google.bigtable.testproxy.CloudBigtableV2TestProxy.CreateClient:output_type -> google.bigtable.testproxy.CreateClientResponse
	4,  // 40: google.bigtable.testproxy.CloudBigtableV2TestProxy.CloseClient:output_type -> google.bigtable.testproxy.CloseClientResponse
	6,  // 41: google.bigtable.testproxy.CloudBigtableV2TestProxy.RemoveClient:output_type -> google.bigtable.testproxy.RemoveClientResponse
	8,  // 42: google.bigtable.testproxy.CloudBigtableV2TestProxy.ReadRow:output_type -> google.bigtable.testproxy.RowResult
	10, // 43: google.bigtable.testproxy.CloudBigtableV2TestProxy.ReadRows:output_type -> google.bigtable.testproxy.RowsResult
	12, // 44: google.bigtable.testproxy.CloudBigtableV2TestProxy.MutateRow:output_type -> google.bigtable.testproxy.MutateRowResult
	14, // 45: google.bigtable.testproxy.CloudBigtableV2TestProxy.BulkMutateRows:output_type -> google.bigtable.testproxy.MutateRowsResult
	16, // 46: google.bigtable.testproxy.CloudBigtableV2TestProxy.CheckAndMutateRow:output_type -> google.bigtable.testproxy.CheckAndMutateRowResult
	18, // 47: google.bigtable.testproxy.CloudBigtableV2TestProxy.SampleRowKeys:output_type -> google.bigtable.testproxy.SampleRowKeysResult
	8,  // 48: google.bigtable.testproxy.CloudBigtableV2TestProxy.ReadModifyWriteRow:output_type -> google.bigtable.testproxy.RowResult
	21, // 49: google.bigtable.testproxy.CloudBigtableV2TestProxy.ExecuteQuery:output_type -> google.bigtable.testproxy.ExecuteQueryResult
	39, // [39:50] is the sub-list for method output_type
	28, // [28:39] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_test_proxy_proto_init() }
func file_test_proxy_proto_init() {
	if File_test_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proxy_proto_rawDesc), len(file_test_proxy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_proxy_proto_goTypes,
		DependencyIndexes: file_test_proxy_proto_depIdxs,
		EnumInfos:         file_test_proxy_proto_enumTypes,
		MessageInfos:      file_test_proxy_proto_msgTypes,
	}.Build()
	File_test_proxy_proto = out.File
	file_test_proxy_proto_goTypes = nil
	file_test_proxy_proto_depIdxs = nil
}
